version: '0.2.{build}'
image: Visual Studio 2017
configuration:
- Debug
- Release
branches:
  only:
    - master
    - test
    - release
    - /dev-.*/
platform: Any CPU
init:
 - ps: $Env:LABEL = "CI" +$Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
# - ps: Start-FileDownload 'https://download.microsoft.com/download/5/F/E/5FEB7E95-C643-48D5-8329-9D2C63676CE8/dotnet-dev-win-x64.1.0.0-rc4-004771.exe'
# - dotnet-dev-win-x64.1.0.0-rc4-004771.exe /quiet
- ps: Start-FileDownload https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
- dotnet-sdk-2.0.0-win-x64.exe /quiet
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
test_script:
- dotnet test .\test\dexih.functions.tests\dexih.functions.tests.csproj
- dotnet test .\test\dexih.functions.tests.async\dexih.functions.tests.async.csproj
- cd test\dexih.connections.azure.tests
- '"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'
- dotnet test 
- cd ..\dexih.connections.flatfile.tests
- dotnet test 
- cd ..\dexih.connections.sql.tests
- dotnet test 
- cd ..\dexih.connections.excel.tests
- dotnet test 
- cd ..\dexih.connections.webservice.restful.tests
- dotnet test 
- cd ..\..
artifacts:
  - path: artifacts\*.nupkg
services:
  - mssql2014
  - mysql
  - postgresql

cache:
 - '%USERPROFILE%\.nuget\packages'

deploy:
 - provider: NuGet
   server: https://www.nuget.org/api/v2/package
   api_key:
     secure: D2Fu0l/iyBVmVqt/yUztGOFPy3FhYdt9DdnYTgr5KvYYSvb+mRstFwoLeEpmZTUN
   skip_symbols: false
   symbol_server: https://www.nuget.org/api/v2/package
   on: 
    branch: 
     - master
     - test
     - release
     
for:

# The release branch publishes without the version suffix, making an official release.
-
  branches:
    only:
      - release

  configuration: Release
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%
  - dotnet pack -c %CONFIGURATION% --no-build -o ../../artifacts
  - del .\artifacts\*test*
  - del .\artifacts\*Example*
  
# test branch produces a nuget package with the version suffix added.
-
  branches:
    only:
      - test

  configuration: Debug
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o ../../artifacts
  - del .\artifacts\*test*
  - del .\artifacts\*Example*
  
# master and dev branchs runs test only, no publishing packages
-
  branches:
    only:
      - master
      - /dev-.*/

  configuration: Debug
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%
  
  
  